# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mmi_charger
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_PD_CHARGER_MMI)),)
	ccflags-y += -DCONFIG_PD_CHARGER_MMI
endif

obj-m += qpnp_smb_basic_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
