# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/drivers/power/mm8013c_fg_mmi

mm8013c_fg_mmi-y += mm8013c_battery.o
obj-m += mm8013c_fg_mmi.o
