# Early-logging level for ff_hal, ff_ta and driver as well. Note that this
# logging level only takes effect before ff_config module is loaded.
#
# Options:
# 0 - FF_LOG_LEVEL_ALL, All
# 1 - FF_LOG_LEVEL_VBS, Verbose
# 2 - FF_LOG_LEVEL_DBG, Debug
# 3 - FF_LOG_LEVEL_INF, Info
# 4 - FF_LOG_LEVEL_WRN, Warning
# 5 - FF_LOG_LEVEL_ERR, Error
EXTRA_CFLAGS += -D__FF_EARLY_LOG_LEVEL=2


focal_fps_mmi-y +=  ff_ctl.o plat-msm.o

ifneq ($(filter m y,$(CONFIG_INPUT_EGISTEC_FPS_NAVI)),)
	ccflags-y += -DCONFIG_INPUT_EGISTEC_FPS_NAVI
	ets_fps_mmi-y += ets_navi_input.o
endif
ifneq ($(filter m y,$(CONFIG_INPUT_EGISTEC_FPS_NAVI_VERTICAL)),)
	ccflags-y += -DCONFIG_INPUT_EGISTEC_FPS_NAVI_VERTICAL
endif
ifneq ($(filter m y,$(CONFIG_FOCAL_SUPPORT_DRM_SCREEN)),)
	ccflags-y += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y, $(CONFIG_FOCAL_PANEL_NOTIFICATIONS)),)
	ccflags-y += -DCONFIG_PANEL_NOTIFICATIONS
endif

obj-$(CONFIG_INPUT_EGISTEC_FPS_NAVI_MMI) += focal_fps_mmi.o
