# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/power/mmi_parallel_charger_qc3p

obj-m += mmi_parallel_charger_qc3p.o
mmi_parallel_charger_qc3p-y += mmi_charger_class.o
mmi_parallel_charger_qc3p-y += mmi_charger_core.o
mmi_parallel_charger_qc3p-y += mmi_charger_pump_policy.o
mmi_parallel_charger_qc3p-y += bq2597x_charger.o
mmi_parallel_charger_qc3p-y += qpnp_pmic_charger.o

#ifeq ($(CONFIG_MMI_PL_CP_POLICY), y)
#endif
