# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/drivers/power/sd77426_fg_mmi

sd77426_fg_mmi-y += oz8806_battery.o
sd77426_fg_mmi-y += parameter.o
sd77426_fg_mmi-y += table.o
sd77426_fg_mmi-y += bmulib.o
sd77426_fg_mmi-y += calculate.o
obj-m += sd77426_fg_mmi.o
