# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(TOP)/motorola/kernel/modules/include \
		-I$(TOP)/motorola/kernel/modules/drivers/power/mmi_pl_chg_manager

obj-m += mmi_pl_chg_manager.o
