# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_CHARGER_BQ2589X)	+= bq2589x_chg_mmi/
obj-$(CONFIG_CW2217B_FG)	+= cw2217b_fg_mmi/
obj-$(CONFIG_USE_MMI_CHARGER)	+= mmi_charger/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE)	+= qpnp_adaptive_charge/
obj-$(CONFIG_MMI_DISCRETE_CHARGER)	+= mmi_discrete_charger/
obj-$(CONFIG_SGM4154X_CHARGER_MMI)	+= sgm4154x_chg_mmi/
obj-$(CONFIG_SM5602_FG_MMI)	+= sm5602_fg_mmi/
