# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(TOP)/motorola/kernel/modules/include

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
    ccflags-y += -DP938X_USER_DEBUG
endif

obj-m += p938x_charger.o
