# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/drivers/power/rt9426a_fg_mmi

rt9426a_fg_mmi-y += rt9426a_battery.o
obj-m += rt9426a_fg_mmi.o
