# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/bq2597x_mmi_iio

obj-m += bq2597x_mmi_iio.o

