ifneq ($(filter m y,$(CONFIG_MMI_QC3P_TURBO_CHARGER)),)
        ccflags-y += -DCONFIG_MMI_QC3P_TURBO_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_WT6670_DETECTED)),)
        ccflags-y += -DCONFIG_MMI_QC3P_WT6670_DETECTED
endif

ifneq ($(filter m y,$(CONFIG_MMI_SGM41513_CHARGER)),)
        ccflags-y += -DCONFIG_MMI_SGM41513_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_Z350_DETECTED)),)
        ccflags-y += -DCONFIG_MMI_QC3P_Z350_DETECTED
endif

obj-$(CONFIG_SGM4154X_CHARGER_MMI) += sgm4154x_charger.o
