ifneq ($(filter m y,$(CONFIG_MMI_QC3P_TURBO_CHARGER)),)
        ccflags-y += -DCONFIG_MMI_QC3P_TURBO_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_WT6670_DETECTED)),)
        ccflags-y += -DCONFIG_MMI_QC3P_WT6670_DETECTED
endif

obj-$(CONFIG_CHARGER_BQ2589X) += bq2589x_charger.o
