ifneq ($(filter m y,$(CONFIG_EGIS_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_ET721_FOD)),)
    EXTRA_CFLAGS += -DET721_FOD
endif

rbs_fps_mmi-y += etxxx_fp.o

obj-$(CONFIG_EGIS_FPS) += rbs_fps_mmi.o
