# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_PD_CHARGER_MMI)),)
	ccflags-y += -DCONFIG_PD_CHARGER_MMI
endif

ifneq ($(filter m y, $(CONFIG_BQ2597X_DUAL)),)
	ccflags-y += -DCONFIG_BQ2597X_DUAL
endif

obj-m += qpnp-smbcharger-mmi.o
