# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/fet_control
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

obj-m += fet_control.o
