# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/mmi_discrete_turbo_charger

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_WT6670_DETECTED)),)
        ccflags-y += -DCONFIG_MMI_QC3P_WT6670_DETECTED
endif

obj-m += mmi_discrete_turbo_charger.o
mmi_discrete_turbo_charger-y += mmi_charger_class.o
mmi_discrete_turbo_charger-y += mmi_charger_core.o
mmi_discrete_turbo_charger-y += mmi_charger_pump_policy.o
mmi_discrete_turbo_charger-y += mmi_cp_charger.o
mmi_discrete_turbo_charger-y += qpnp_pmic_charger.o
mmi_discrete_turbo_charger-y += mmi_qc3p.o
mmi_discrete_turbo_charger-y += mmi_qc3p_cp_policy.o

#ifeq ($(CONFIG_MMI_PL_CP_POLICY), y)
#endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../usb/typec/adapter_class/$(GKI_OBJ_MODULE_DIR)/Module.symvers
